# Site Settings
baseurl: 		""
title: 			Insurance for Freelancers

name: 			Insurance for freelancers
description: 	Professional indemnity, public liability and professional indemnity. We explain business insurance for freelancers.
url: 			"http://insuranceforfreelancers.co.uk"

twitter: 		insurancebyjack
email: 			hello@insurancebyjack.co.uk

analytics: 		UA-XXXXXXX-Y